name: Deploy ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run pipeline on server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connecting to server..."

            cd /home/ubuntu/immo/ML-Project-Real-Estate-prediction

            echo "Pulling latest code..."
            git pull origin main

            echo "Running pipeline..."
            bash pipeline.sh

            echo "Deployment complete"
